name: iautomat_auth_manager
description: "A robust Flutter package for authentication management with Firebase Auth using email and password. Features Result pattern, comprehensive error handling, and full test coverage."
version: 1.0.0
homepage: https://github.com/yourusername/iautomat_auth_manager
repository: https://github.com/yourusername/iautomat_auth_manager
issue_tracker: https://github.com/yourusername/iautomat_auth_manager/issues
documentation: https://github.com/yourusername/iautomat_auth_manager#readme

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

topics:
  - flutter
  - firebase
  - authentication
  - auth
  - firebase-auth
  - email-password
  - result-pattern
  - dart

platforms:
  android:
  ios:
  web:

# The following section is specific to Flutter packages.
flutter:
